# Generated by Django 2.2 on 2020-02-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='device_id',
        ),
    ]
