# Generated by Django 2.2 on 2020-02-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_auto_20200209_1510"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatroom",
            options={"ordering": ["-last_message_time"]},
        ),
        migrations.AlterModelOptions(
            name="messages",
            options={"ordering": ["-date_time_creation"]},
        ),
        migrations.AddField(
            model_name="messages",
            name="chat_room_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_room_id",
                to="app.ChatRoom",
            ),
            preserve_default=False,
        ),
    ]
