# Generated by Django 2.2 on 2020-02-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200210_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'ordering': ['-date_time_creation']},
        ),
    ]
