# Generated by Django 2.2 on 2020-03-14 13:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200217_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_message_body',
            field=models.TextField(default='message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_message_sender',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, related_name='last_message_sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
